### ISSUE TITLE
when I run "pip3 install py-imessage", I got this. (normal when running install other package)

### ISSUE THREAD

**Issue by fishmisswater** [Rolstenhouse/py-iMessage#4]
Collecting py-imessage
  Downloading py-iMessage-1.7.tar.gz (6.3 kB)
    ERROR: Command errored out with exit status 1:
     command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-HUY3wS/py-imessage/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-HUY3wS/py-imessage/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-p6vHkC
         cwd: /private/tmp/pip-install-HUY3wS/py-imessage/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-HUY3wS/py-imessage/setup.py", line 13, in <module>
        with open (join(dirname(__file__), 'requirements.txt'), 'r') as f:
    IOError: [Errno 2] No such file or directory: '/private/tmp/pip-install-HUY3wS/py-imessage/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

my OS is MAC 10.15 ,  and I run it in vmware

**Comment by Rolstenhouse** [comment]
Hmm. Let me see if I can reproduce on my machine and figure it out. 

You are going to run into issues using VMWare however, Apple often checks if a certain flag is set at the hardware level for the Messages App (unlike other pieces of software). 

Are you able to send iMessages from the VMWare image already?

**Comment by fishmisswater** [comment]
Yes, I'm running it in VMWare.

**Comment by sam-ghala** [comment]
I am also getting this issue
