### ISSUE TITLE
keyerror

### ISSUE THREAD

**Issue by justanothernoob4648** [Rolstenhouse/py-iMessage#8]
Traceback (most recent call last):
  File "c:/Users/Desktop/gmailpy/emailpyspam/spammer.py", line 59, in <module>
    from py_imessage import imessage
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\py_imessage\imessage.py", line 1, in <module>
    from py_imessage import db_conn
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\py_imessage\db_conn.py", line 11, in <module>
    home = os.environ['HOME']
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'

**Comment by mardax007** [comment]
I have the same issue(also on pc).
I think it can only be run on a mac.
Can @Rolstenhouse please specify that in the readme?
